import type { INodeProperties } from 'n8n-workflow';

export const corporateActionsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['corporateActions'] } },
		options: [
			{ name: 'Claim Dividend', value: 'claimDividend', description: 'Claim dividend payment', action: 'Claim dividend' },
			{ name: 'Create Checkpoint', value: 'createCheckpoint', description: 'Create balance checkpoint', action: 'Create checkpoint' },
			{ name: 'Create Checkpoint Schedule', value: 'createCheckpointSchedule', description: 'Schedule recurring checkpoints', action: 'Create checkpoint schedule' },
			{ name: 'Create Dividend Distribution', value: 'createDividendDistribution', description: 'Create dividend distribution', action: 'Create dividend distribution' },
			{ name: 'Get Checkpoint Balance', value: 'getCheckpointBalance', description: 'Get balance at checkpoint', action: 'Get checkpoint balance' },
			{ name: 'Get Checkpoints', value: 'getCheckpoints', description: 'Get asset checkpoints', action: 'Get checkpoints' },
			{ name: 'Get Corporate Actions', value: 'getCorporateActions', description: 'Get all corporate actions', action: 'Get corporate actions' },
			{ name: 'Get Distribution Targets', value: 'getDistributionTargets', description: 'Get distribution recipients', action: 'Get distribution targets' },
			{ name: 'Get Dividend Distribution', value: 'getDividendDistribution', description: 'Get dividend details', action: 'Get dividend distribution' },
			{ name: 'Push Dividend Payment', value: 'pushDividendPayment', description: 'Push payment to recipients', action: 'Push dividend payment' },
			{ name: 'Reclaim Dividend', value: 'reclaimDividend', description: 'Reclaim unclaimed funds', action: 'Reclaim dividend' },
		],
		default: 'getCorporateActions',
	},
];

export const corporateActionsFields: INodeProperties[] = [
	// Ticker field for most operations
	{
		displayName: 'Asset Ticker',
		name: 'ticker',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'] } },
		default: '',
		description: 'The ticker symbol of the asset',
	},
	// Distribution ID
	{
		displayName: 'Distribution ID',
		name: 'distributionId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['getDividendDistribution', 'claimDividend', 'pushDividendPayment', 'reclaimDividend', 'getDistributionTargets'] } },
		default: '',
		description: 'The ID of the dividend distribution',
	},
	// Checkpoint ID
	{
		displayName: 'Checkpoint ID',
		name: 'checkpointId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution', 'getCheckpointBalance'] } },
		default: '',
		description: 'The checkpoint ID to use',
	},
	// DID for checkpoint balance
	{
		displayName: 'Identity DID',
		name: 'did',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['getCheckpointBalance'] } },
		default: '',
		description: 'The DID to get balance for',
	},
	// Create dividend distribution fields
	{
		displayName: 'Origin Portfolio ID',
		name: 'originPortfolioId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution'] } },
		default: '0',
		description: 'Portfolio ID for distribution funds (0 for default)',
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution'] } },
		default: 'POLYX',
		description: 'Currency ticker for distribution',
	},
	{
		displayName: 'Per Share Amount',
		name: 'perShare',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution'] } },
		default: '',
		description: 'Amount per share (in smallest unit)',
	},
	{
		displayName: 'Max Amount',
		name: 'maxAmount',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution'] } },
		default: '',
		description: 'Maximum total distribution amount',
	},
	{
		displayName: 'Payment Date',
		name: 'paymentDate',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution'] } },
		default: '',
		description: 'Date when payments can be claimed',
	},
	{
		displayName: 'Expiry Date',
		name: 'expiryDate',
		type: 'dateTime',
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution'] } },
		default: '',
		description: 'Optional expiry date for claims',
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createDividendDistribution'] } },
		default: '',
		description: 'Description of the distribution',
	},
	// Targets for push payment
	{
		displayName: 'Target DIDs',
		name: 'targets',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['pushDividendPayment'] } },
		default: '',
		description: 'Comma-separated list of target DIDs',
	},
	// Checkpoint schedule fields
	{
		displayName: 'Start Date',
		name: 'start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createCheckpointSchedule'] } },
		default: '',
		description: 'Schedule start date',
	},
	{
		displayName: 'Period',
		name: 'period',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createCheckpointSchedule'] } },
		options: [
			{ name: 'Daily', value: 'daily' },
			{ name: 'Weekly', value: 'weekly' },
			{ name: 'Monthly', value: 'monthly' },
			{ name: 'Quarterly', value: 'quarterly' },
			{ name: 'Yearly', value: 'yearly' },
		],
		default: 'monthly',
		description: 'Checkpoint frequency',
	},
	{
		displayName: 'Repetitions',
		name: 'repetitions',
		type: 'number',
		displayOptions: { show: { resource: ['corporateActions'], operation: ['createCheckpointSchedule'] } },
		default: 0,
		description: 'Number of repetitions (0 for unlimited)',
	},
];
