import type { INodeProperties } from 'n8n-workflow';

export const checkpointOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['checkpoint'] } },
		options: [
			{ name: 'Create Checkpoint', value: 'createAssetCheckpoint', description: 'Create a balance checkpoint', action: 'Create checkpoint' },
			{ name: 'Create Schedule', value: 'createSchedule', description: 'Create recurring checkpoint schedule', action: 'Create schedule' },
			{ name: 'Get Checkpoint Balance', value: 'getCheckpointBalanceFor', description: 'Get balance at checkpoint for identity', action: 'Get checkpoint balance' },
			{ name: 'Get Checkpoint Details', value: 'getCheckpointDetails', description: 'Get checkpoint details', action: 'Get checkpoint details' },
			{ name: 'Get Checkpoint Schedules', value: 'getCheckpointSchedules', description: 'Get checkpoint schedules', action: 'Get checkpoint schedules' },
			{ name: 'Get Checkpoints', value: 'getCheckpointsForAsset', description: 'Get all checkpoints for asset', action: 'Get checkpoints' },
			{ name: 'Get Holders at Checkpoint', value: 'getHoldersAtCheckpoint', description: 'Get all holders at checkpoint', action: 'Get holders at checkpoint' },
			{ name: 'Get Total Supply at Checkpoint', value: 'getTotalSupplyAtCheckpoint', description: 'Get total supply at checkpoint', action: 'Get total supply at checkpoint' },
			{ name: 'Remove Schedule', value: 'removeSchedule', description: 'Remove a checkpoint schedule', action: 'Remove schedule' },
		],
		default: 'getCheckpointsForAsset',
	},
];

export const checkpointFields: INodeProperties[] = [
	{
		displayName: 'Asset Ticker',
		name: 'ticker',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['checkpoint'] } },
		default: '',
		description: 'The ticker symbol of the asset',
	},
	{
		displayName: 'Checkpoint ID',
		name: 'checkpointId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['checkpoint'], operation: ['getCheckpointDetails', 'getCheckpointBalanceFor', 'getTotalSupplyAtCheckpoint', 'getHoldersAtCheckpoint'] } },
		default: '',
		description: 'The checkpoint ID',
	},
	{
		displayName: 'Identity DID',
		name: 'did',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['checkpoint'], operation: ['getCheckpointBalanceFor'] } },
		default: '',
		description: 'The DID to get balance for',
	},
	{
		displayName: 'Schedule ID',
		name: 'scheduleId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['checkpoint'], operation: ['removeSchedule'] } },
		default: '',
		description: 'The schedule ID to remove',
	},
	{
		displayName: 'Start Date',
		name: 'start',
		type: 'dateTime',
		required: true,
		displayOptions: { show: { resource: ['checkpoint'], operation: ['createSchedule'] } },
		default: '',
		description: 'Schedule start date',
	},
	{
		displayName: 'Period Unit',
		name: 'periodUnit',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['checkpoint'], operation: ['createSchedule'] } },
		options: [
			{ name: 'Days', value: 'Days' },
			{ name: 'Weeks', value: 'Weeks' },
			{ name: 'Months', value: 'Months' },
			{ name: 'Years', value: 'Years' },
		],
		default: 'Months',
		description: 'Period unit for schedule',
	},
	{
		displayName: 'Period Amount',
		name: 'periodAmount',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['checkpoint'], operation: ['createSchedule'] } },
		default: 1,
		description: 'Number of period units',
	},
	{
		displayName: 'Repetitions',
		name: 'repetitions',
		type: 'number',
		displayOptions: { show: { resource: ['checkpoint'], operation: ['createSchedule'] } },
		default: 0,
		description: 'Number of repetitions (0 for unlimited)',
	},
];
