import type { INodeProperties } from 'n8n-workflow';

export const utilityOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['utility'] } },
		options: [
			{ name: 'Convert Units', value: 'convertUnits', description: 'Convert POLYX units', action: 'Convert units' },
			{ name: 'Decode Address', value: 'decodeAddress', description: 'Decode SS58 address', action: 'Decode address' },
			{ name: 'Encode Address', value: 'encodeAddress', description: 'Encode public key to address', action: 'Encode address' },
			{ name: 'Estimate Transaction Fee', value: 'estimateTransactionFee', description: 'Estimate transaction fee', action: 'Estimate transaction fee' },
			{ name: 'Get Block Details', value: 'getBlockDetails', description: 'Get block information', action: 'Get block details' },
			{ name: 'Get Chain Metadata', value: 'getChainMetadata', description: 'Get chain metadata', action: 'Get chain metadata' },
			{ name: 'Get DID from Address', value: 'getDidFromAddress', description: 'Get DID linked to address', action: 'Get DID from address' },
			{ name: 'Get Latest Block', value: 'getLatestBlock', description: 'Get latest block number', action: 'Get latest block' },
			{ name: 'Get Network Info', value: 'getNetworkInformation', description: 'Get network information', action: 'Get network info' },
			{ name: 'Get Protocol Fees', value: 'getProtocolFees', description: 'Get protocol fees', action: 'Get protocol fees' },
			{ name: 'Validate Address', value: 'validateAddress', description: 'Validate Polymesh address', action: 'Validate address' },
			{ name: 'Validate DID', value: 'validateDid', description: 'Validate DID format', action: 'Validate DID' },
		],
		default: 'getNetworkInformation',
	},
];

export const utilityFields: INodeProperties[] = [
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['utility'], operation: ['convertUnits'] } },
		default: '',
		description: 'Amount to convert',
	},
	{
		displayName: 'Conversion Direction',
		name: 'conversionDirection',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['utility'], operation: ['convertUnits'] } },
		options: [
			{ name: 'POLYX to Micro', value: 'toMicro', description: 'Convert POLYX to micro units' },
			{ name: 'Micro to POLYX', value: 'fromMicro', description: 'Convert micro units to POLYX' },
		],
		default: 'toMicro',
		description: 'Direction of conversion',
	},
	{
		displayName: 'Public Key',
		name: 'publicKey',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['utility'], operation: ['encodeAddress'] } },
		default: '',
		description: 'Public key to encode (hex)',
	},
	{
		displayName: 'Address',
		name: 'address',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['utility'], operation: ['decodeAddress', 'validateAddress', 'getDidFromAddress'] } },
		default: '',
		description: 'Polymesh address',
	},
	{
		displayName: 'DID',
		name: 'did',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['utility'], operation: ['validateDid'] } },
		default: '',
		description: 'DID to validate',
	},
	{
		displayName: 'Block Number',
		name: 'blockNumber',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['utility'], operation: ['getBlockDetails'] } },
		default: '',
		description: 'Block number to query',
	},
	{
		displayName: 'Transaction Tag',
		name: 'transactionTag',
		type: 'options',
		displayOptions: { show: { resource: ['utility'], operation: ['getProtocolFees'] } },
		options: [
			{ name: 'Asset - Register Ticker', value: 'asset.registerTicker' },
			{ name: 'Asset - Create Asset', value: 'asset.createAsset' },
			{ name: 'Asset - Issue', value: 'asset.issue' },
			{ name: 'Identity - CDD Register Did', value: 'identity.cddRegisterDid' },
			{ name: 'Settlement - Create Venue', value: 'settlement.createVenue' },
			{ name: 'Settlement - Add Instruction', value: 'settlement.addInstruction' },
			{ name: 'Checkpoint - Create Checkpoint', value: 'checkpoint.createCheckpoint' },
			{ name: 'Corporate Action - Initiate', value: 'corporateAction.initiateCorporateAction' },
		],
		default: 'asset.registerTicker',
		description: 'Transaction type for fee lookup',
	},
	{
		displayName: 'Transaction Type',
		name: 'transactionType',
		type: 'options',
		displayOptions: { show: { resource: ['utility'], operation: ['estimateTransactionFee'] } },
		options: [
			{ name: 'Asset - Register Ticker', value: 'asset.registerTicker' },
			{ name: 'Asset - Create Asset', value: 'asset.createAsset' },
			{ name: 'Asset - Issue', value: 'asset.issue' },
			{ name: 'Identity - CDD Register Did', value: 'identity.cddRegisterDid' },
			{ name: 'Settlement - Create Venue', value: 'settlement.createVenue' },
			{ name: 'Settlement - Add Instruction', value: 'settlement.addInstruction' },
		],
		default: 'asset.registerTicker',
		description: 'Transaction type to estimate',
	},
	{
		displayName: 'Asset Ticker',
		name: 'ticker',
		type: 'string',
		displayOptions: { show: { resource: ['utility'], operation: ['estimateTransactionFee'] } },
		default: '',
		description: 'Optional ticker for asset-related transactions',
	},
];
