import type { INodeProperties } from 'n8n-workflow';

export const stoOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['sto'] } },
		options: [
			{ name: 'Close Fundraiser', value: 'closeFundraiser', description: 'Close a fundraiser', action: 'Close fundraiser' },
			{ name: 'Create Fundraiser', value: 'createFundraiser', description: 'Launch a security token offering', action: 'Create fundraiser' },
			{ name: 'Freeze Fundraiser', value: 'freezeFundraiser', description: 'Freeze a fundraiser', action: 'Freeze fundraiser' },
			{ name: 'Get All Offerings', value: 'getAllOfferings', description: 'Get all offerings for asset', action: 'Get all offerings' },
			{ name: 'Get Investments', value: 'getInvestments', description: 'Get investments in offering', action: 'Get investments' },
			{ name: 'Get STO Details', value: 'getStoDetails', description: 'Get offering details', action: 'Get STO details' },
			{ name: 'Invest in Fundraiser', value: 'investInFundraiser', description: 'Invest in a security token offering', action: 'Invest in fundraiser' },
			{ name: 'Modify Fundraiser Times', value: 'modifyFundraiserTimes', description: 'Modify start/end times', action: 'Modify fundraiser times' },
			{ name: 'Unfreeze Fundraiser', value: 'unfreezeFundraiser', description: 'Unfreeze a fundraiser', action: 'Unfreeze fundraiser' },
		],
		default: 'getStoDetails',
	},
];

export const stoFields: INodeProperties[] = [
	{
		displayName: 'Asset Ticker',
		name: 'ticker',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'] } },
		default: '',
		description: 'The ticker symbol of the asset',
	},
	{
		displayName: 'STO ID',
		name: 'stoId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['getStoDetails', 'modifyFundraiserTimes', 'freezeFundraiser', 'unfreezeFundraiser', 'closeFundraiser', 'investInFundraiser', 'getInvestments'] } },
		default: '',
		description: 'The ID of the security token offering',
	},
	// Create fundraiser fields
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser'] } },
		default: '',
		description: 'Name of the offering',
	},
	{
		displayName: 'Raising Currency',
		name: 'raisingCurrency',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser'] } },
		default: 'POLYX',
		description: 'Currency ticker to raise (e.g., POLYX or stablecoin)',
	},
	{
		displayName: 'Offering Portfolio ID',
		name: 'offeringPortfolioId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser'] } },
		default: '0',
		description: 'Portfolio ID containing tokens to sell (0 for default)',
	},
	{
		displayName: 'Raising Portfolio ID',
		name: 'raisingPortfolioId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser'] } },
		default: '0',
		description: 'Portfolio ID to receive raised funds (0 for default)',
	},
	{
		displayName: 'Tiers',
		name: 'tiers',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser'] } },
		default: {},
		options: [
			{
				name: 'tierValues',
				displayName: 'Tier',
				values: [
					{ displayName: 'Price', name: 'price', type: 'string', default: '', description: 'Price per token (smallest unit)' },
					{ displayName: 'Amount', name: 'amount', type: 'string', default: '', description: 'Amount of tokens in tier' },
				],
			},
		],
		description: 'Offering tiers with different prices',
	},
	{
		displayName: 'Start Date',
		name: 'start',
		type: 'dateTime',
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser', 'modifyFundraiserTimes'] } },
		default: '',
		description: 'Start date of the offering',
	},
	{
		displayName: 'End Date',
		name: 'end',
		type: 'dateTime',
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser', 'modifyFundraiserTimes'] } },
		default: '',
		description: 'End date of the offering',
	},
	{
		displayName: 'Minimum Investment',
		name: 'minInvestment',
		type: 'string',
		displayOptions: { show: { resource: ['sto'], operation: ['createFundraiser'] } },
		default: '',
		description: 'Minimum investment amount',
	},
	// Invest fields
	{
		displayName: 'Purchase Amount',
		name: 'purchaseAmount',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['investInFundraiser'] } },
		default: '',
		description: 'Amount of tokens to purchase',
	},
	{
		displayName: 'Max Price',
		name: 'maxPrice',
		type: 'string',
		displayOptions: { show: { resource: ['sto'], operation: ['investInFundraiser'] } },
		default: '',
		description: 'Maximum price willing to pay',
	},
	{
		displayName: 'Funding Portfolio ID',
		name: 'fundingPortfolioId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['investInFundraiser'] } },
		default: '0',
		description: 'Portfolio ID with raising currency (0 for default)',
	},
	{
		displayName: 'Purchase Portfolio ID',
		name: 'purchasePortfolioId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['sto'], operation: ['investInFundraiser'] } },
		default: '0',
		description: 'Portfolio ID to receive tokens (0 for default)',
	},
];
